### ISSUE TITLE
cluttered emacs. Needs tabspaces = 8

### ISSUE THREAD

**Issue by christophgil** [justanoobcoder/st#1]
I am running emacs -nw in this st version.
This st configuration comes closest to what I am used from xfce4 or gnome terminal.
Only missing Ctrl-Plus Ctrl-Minus for zooming.

st is a very nice terminal which takes only little resources.

I found 2 Issues:

In emacs, the display gets cluttered sometimes on tab word completion.
Changing
unsigned int tabspaces = 4;
to
unsigned int tabspaces = 8;
fixes this problem.

Furthermore the font JetBrainsMono was not shown properly and I had to change it to 
Liberation Mono:pixelsize=12:antialias=true:autohint=true

**Comment by justanoobcoder** [comment]
Hi. About the cluttered emacs issue, when I changed tabspaces to 4 (default was 8), I forgot to changed one value in st.info file (which I should have). I think that is the problem. I've already changed it, so could you clone this repo again and see if it fixes the problem and feedback to me? If it does not, I will change tabspaces to 8. About the font problem, perhaps you install wrong font. The default font in this st is JetBrainsMono Nerd Font which you can download from [here](https://www.nerdfonts.com/font-downloads) or you can install [nerd-fonts-jetbrains-mono](https://aur.archlinux.org/packages/nerd-fonts-jetbrains-mono) from AUR if you use Arch linux. 

I also added ctrl -/+ for zooming since it's default on most terminal. Thanks for reporting.

**Comment by christophgil** [comment]
Hi Nguyen,

Cool thanks so much,

Actually zoom in is not Ctrl-+ but Ctrl-=
Maybe because plus and equals are on the same key?

Regarding the fonts I did the following without success
sudo apt-get install fonts-jetbrains-mono

This is the only font reported with
apt-cache search  jetbrains

Cheers

Christoph

**Comment by justanoobcoder** [comment]
yeah, = and + key are on same button, so it's = not + to make it work. The font is not jetbrains mono font, it's jetbrains mono nerd font. Nerd fonts are fonts that are patched with icons (help to display icons properly). So you must download from [here](https://www.nerdfonts.com/font-downloads), extract it and put otf, ttf files in ~/.local/share/fonts, then run `fc-cache -f`. I don't think you can install it from apt-get. But font is just a personal thing, you don't have to use font like mine. Just use whatever works

**Comment by christophgil** [comment]
Very nice font, indeed. Looks much smoother.

I have no idea, why this line is not working:

{ ControlMask,          XK_plus,       zoom,           {.f = +1} },
I also tried without success
{ ControlMask|ShiftMask,          XK_equals,       zoom,           {.f =
+1} },

**Comment by justanoobcoder** [comment]
It's actually XK_equal, not XK_equals. Seems like XK_plus doesn't work with Ctrl key

**Comment by christophgil** [comment]
Hi Nguyen,

st is working perfectly - thanks so much.

One question: I ssh into another machine and run emacs in no-window-mode as
a tui program.

I am pasting text with middle click  or  ctrl-shift-v.
I am surprised that the pasted text goes into the emacs selection/killring.

How does emacs know that the text was pasted.
Is pasting text not the same as  quickly typing?

is  st sending something special  to emacs.

I would like to avoid pasted text to go into the  emacs  killring.

Best

Christoph


best Christoph

**Comment by justanoobcoder** [comment]
Hi Christoph,
About this behavior, it seems like it's because of bracketed paste mode. Basically, if the terminal supports this feature, when you paste something, around the pasted text will have a special "bracket". These bracket will tell the text editor "this is a pasted text". That's how emacs knows the text was pasted. st is one of those terminals which support this feature by default. I did some research and found out that to disable this feature, you have to change the value of `allowaltscreen` variable line 50 in `config.def.h` file to 0. I'm not sure it would work. If it doesn't work, you might want to do some research about how to disable it in emacs. I think there are many ways to disable it, not only on st

**Comment by christophgil** [comment]
Thanks, I'll check it out.

**Comment by christophgil** [comment]
Great, many thanks.
Deaktivating the two lines
     if (IS_SET(MODE_BRCKTPASTE) && ofs == 0) ttywrite(...

did the trick.
